export const STARTER_PACKS = [
	{
		packID: 'clicker_starter',
		packName: 'Starter Pack',
		description: '3 cards • Standard to Uncommon',
		price: 1000,
		pack: null,
		packColor: '#9e9e9e',
		maxPurchases: 3,
		filter: {},
		packSequence: [
			{ standard: 40, common: 45, uncommon: 15, rare: 0, epic: 0, exotic: 0, legendary: 0, mystic: 0 },
			{ standard: 40, common: 45, uncommon: 15, rare: 0, epic: 0, exotic: 0, legendary: 0, mystic: 0 },
			{ standard: 30, common: 50, uncommon: 20, rare: 0, epic: 0, exotic: 0, legendary: 0, mystic: 0 },
		],
	},
	{
		packID: 'clicker_bronze',
		packName: 'Bronze Pack',
		description: '3 cards • Common to Rare chance',
		price: 5000,
		pack: null,
		packColor: '#cd7f32',
		maxPurchases: 3,
		filter: {},
		packSequence: [
			{ standard: 10, common: 50, uncommon: 35, rare: 5, epic: 0, exotic: 0, legendary: 0, mystic: 0 },
			{ standard: 10, common: 50, uncommon: 35, rare: 5, epic: 0, exotic: 0, legendary: 0, mystic: 0 },
			{ standard: 5, common: 40, uncommon: 45, rare: 10, epic: 0, exotic: 0, legendary: 0, mystic: 0 },
		],
	},
	{
		packID: 'clicker_silver',
		packName: 'Silver Pack',
		description: '4 cards • Uncommon+ with Epic chance',
		price: 15000,
		pack: null,
		packColor: '#c0c0c0',
		maxPurchases: 3,
		filter: {},
		packSequence: [
			{ standard: 0, common: 20, uncommon: 50, rare: 25, epic: 5, exotic: 0, legendary: 0, mystic: 0 },
			{ standard: 0, common: 20, uncommon: 50, rare: 25, epic: 5, exotic: 0, legendary: 0, mystic: 0 },
			{ standard: 0, common: 15, uncommon: 45, rare: 32, epic: 8, exotic: 0, legendary: 0, mystic: 0 },
			{ standard: 0, common: 10, uncommon: 40, rare: 38, epic: 12, exotic: 0, legendary: 0, mystic: 0 },
		],
	},
	{
		packID: 'clicker_gold',
		packName: 'Gold Pack',
		description: '5 cards • Rare+ guaranteed',
		price: 50000,
		pack: null,
		packColor: '#ffd700',
		maxPurchases: 3,
		filter: {},
		packSequence: [
			{ standard: 0, common: 0, uncommon: 0, rare: 60, epic: 30, exotic: 8, legendary: 2, mystic: 0 },
			{ standard: 0, common: 0, uncommon: 0, rare: 60, epic: 30, exotic: 8, legendary: 2, mystic: 0 },
			{ standard: 0, common: 0, uncommon: 0, rare: 55, epic: 32, exotic: 10, legendary: 3, mystic: 0 },
			{ standard: 0, common: 0, uncommon: 0, rare: 50, epic: 35, exotic: 12, legendary: 3, mystic: 0 },
			{ standard: 0, common: 0, uncommon: 0, rare: 45, epic: 38, exotic: 13, legendary: 4, mystic: 0 },
		],
	},
];
